-include php_scws.dep
php_scws.lo: /Users/stuart/sites/minepro/scws/phpext/php_scws.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/stuart/sites/minepro/scws/phpext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -I/Users/stuart/sites/minepro/scws/phpext -I/Users/stuart/sites/minepro/scws/phpext/libscws -DZEND_COMPILE_DL_EXT=1 -c /Users/stuart/sites/minepro/scws/phpext/php_scws.c -o php_scws.lo  -MMD -MF php_scws.dep -MT php_scws.lo
-include libscws/charset.dep
libscws/charset.lo: /Users/stuart/sites/minepro/scws/phpext/libscws/charset.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/stuart/sites/minepro/scws/phpext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -I/Users/stuart/sites/minepro/scws/phpext -I/Users/stuart/sites/minepro/scws/phpext/libscws -DZEND_COMPILE_DL_EXT=1 -c /Users/stuart/sites/minepro/scws/phpext/libscws/charset.c -o libscws/charset.lo  -MMD -MF libscws/charset.dep -MT libscws/charset.lo
-include libscws/darray.dep
libscws/darray.lo: /Users/stuart/sites/minepro/scws/phpext/libscws/darray.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/stuart/sites/minepro/scws/phpext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -I/Users/stuart/sites/minepro/scws/phpext -I/Users/stuart/sites/minepro/scws/phpext/libscws -DZEND_COMPILE_DL_EXT=1 -c /Users/stuart/sites/minepro/scws/phpext/libscws/darray.c -o libscws/darray.lo  -MMD -MF libscws/darray.dep -MT libscws/darray.lo
-include libscws/pool.dep
libscws/pool.lo: /Users/stuart/sites/minepro/scws/phpext/libscws/pool.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/stuart/sites/minepro/scws/phpext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -I/Users/stuart/sites/minepro/scws/phpext -I/Users/stuart/sites/minepro/scws/phpext/libscws -DZEND_COMPILE_DL_EXT=1 -c /Users/stuart/sites/minepro/scws/phpext/libscws/pool.c -o libscws/pool.lo  -MMD -MF libscws/pool.dep -MT libscws/pool.lo
-include libscws/rule.dep
libscws/rule.lo: /Users/stuart/sites/minepro/scws/phpext/libscws/rule.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/stuart/sites/minepro/scws/phpext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -I/Users/stuart/sites/minepro/scws/phpext -I/Users/stuart/sites/minepro/scws/phpext/libscws -DZEND_COMPILE_DL_EXT=1 -c /Users/stuart/sites/minepro/scws/phpext/libscws/rule.c -o libscws/rule.lo  -MMD -MF libscws/rule.dep -MT libscws/rule.lo
-include libscws/scws.dep
libscws/scws.lo: /Users/stuart/sites/minepro/scws/phpext/libscws/scws.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/stuart/sites/minepro/scws/phpext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -I/Users/stuart/sites/minepro/scws/phpext -I/Users/stuart/sites/minepro/scws/phpext/libscws -DZEND_COMPILE_DL_EXT=1 -c /Users/stuart/sites/minepro/scws/phpext/libscws/scws.c -o libscws/scws.lo  -MMD -MF libscws/scws.dep -MT libscws/scws.lo
-include libscws/xdb.dep
libscws/xdb.lo: /Users/stuart/sites/minepro/scws/phpext/libscws/xdb.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/stuart/sites/minepro/scws/phpext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -I/Users/stuart/sites/minepro/scws/phpext -I/Users/stuart/sites/minepro/scws/phpext/libscws -DZEND_COMPILE_DL_EXT=1 -c /Users/stuart/sites/minepro/scws/phpext/libscws/xdb.c -o libscws/xdb.lo  -MMD -MF libscws/xdb.dep -MT libscws/xdb.lo
-include libscws/lock.dep
libscws/lock.lo: /Users/stuart/sites/minepro/scws/phpext/libscws/lock.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/stuart/sites/minepro/scws/phpext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -I/Users/stuart/sites/minepro/scws/phpext -I/Users/stuart/sites/minepro/scws/phpext/libscws -DZEND_COMPILE_DL_EXT=1 -c /Users/stuart/sites/minepro/scws/phpext/libscws/lock.c -o libscws/lock.lo  -MMD -MF libscws/lock.dep -MT libscws/lock.lo
-include libscws/xdict.dep
libscws/xdict.lo: /Users/stuart/sites/minepro/scws/phpext/libscws/xdict.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/stuart/sites/minepro/scws/phpext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -I/Users/stuart/sites/minepro/scws/phpext -I/Users/stuart/sites/minepro/scws/phpext/libscws -DZEND_COMPILE_DL_EXT=1 -c /Users/stuart/sites/minepro/scws/phpext/libscws/xdict.c -o libscws/xdict.lo  -MMD -MF libscws/xdict.dep -MT libscws/xdict.lo
-include libscws/xtree.dep
libscws/xtree.lo: /Users/stuart/sites/minepro/scws/phpext/libscws/xtree.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/stuart/sites/minepro/scws/phpext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -I/Users/stuart/sites/minepro/scws/phpext -I/Users/stuart/sites/minepro/scws/phpext/libscws -DZEND_COMPILE_DL_EXT=1 -c /Users/stuart/sites/minepro/scws/phpext/libscws/xtree.c -o libscws/xtree.lo  -MMD -MF libscws/xtree.dep -MT libscws/xtree.lo
$(phplibdir)/scws.la: ./scws.la
	$(LIBTOOL) --tag=CC --mode=install cp ./scws.la $(phplibdir)

./scws.la: $(shared_objects_scws) $(SCWS_SHARED_DEPENDENCIES)
	$(LIBTOOL) --tag=CC --mode=link $(CC) -shared $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS)  -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_scws) $(SCWS_SHARED_LIBADD)

